### ISSUE TITLE
NOT A BUG

### ISSUE THREAD

**Issue by AFrenchCroissant** [AlexProgrammerDE/balena-minecraft-server#119] opened 2021-03-30 18:56 UTC
Hey is it possible to display a webpage with the players online and a basic webpage on the screen using the browser block

**Comment by AlexProgrammerDE** [comment] 2021-04-14 06:48
@AFrenchCroissant surely! But the problem is that 1. You will have to find a plugin that hosts the website itself. (Maybe the plugin plan?) And 2. Add the browser block.
I think it is possible, but gets a bit off-topic. If you were able to find the right plugin for that and were able to host the website I may be able to help you with setting the browser block up. I will close this issue for now. Let me know if you got the website working. 👍🏻

**Closed by AlexProgrammerDE** 2021-04-14 06:48 UTC
Labels: bug
