### ISSUE TITLE
[BUG] 1.18 needs Java 17

### ISSUE THREAD

**Issue by MiniGPT** [AlexProgrammerDE/balena-minecraft-server#177] opened 2021-11-21 10:16 UTC
1.18 pre-2 update changed the required version to run the game. It now requires Java 17 instead of Java 16.

This is the error on the dashboard:
 mc-server  Checking server JAR... Found a valid server file. It's called: paper.jar. Use ENABLE_UPDATE to update.
 mc-server  Starting JAR file with: 3G of RAM
 mc-server  Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
 mc-server      java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0

![image](https://user-images.githubusercontent.com/33954221/142757972-5577b98f-4cef-4c44-af99-8121ac9f4653.png)

Do I need to update it manually or should I just wait?

**Comment by JonasCardoso** [comment] 2021-12-01 02:10
how to do this manual? i tried use 'FROM openjdk/openjdk:17-jdk-buster', but dont work @MiniGPT

**Comment by MiniGPT** [comment] 2021-12-01 08:40
> how to do this manually ? i tried use 'FROM openjdk:17-jdk-buster', but dont work @MiniGPT 

Balena probably didn't release java 17, but I think that fabric 1.18 is using java 16 , maybe try using that version

**Comment by JonasCardoso** [comment] 2021-12-01 15:51
> > how to do this manually ? i tried use 'FROM openjdk:17-jdk-buster', but dont work @MiniGPT
> 
> Balena probably didn't release java 17, but I think that fabric 1.18 is using java 16 , maybe try using that version

I fixed the problem by doing a workaround to install jdk 17 with the mc-server script, works, but it's not ideal

**Comment by stevereno30** [comment] 2021-12-01 20:48
> > > how to do this manually ? i tried use 'FROM openjdk:17-jdk-buster', but dont work @MiniGPT
> > 
> > 
> > Balena probably didn't release java 17, but I think that fabric 1.18 is using java 16 , maybe try using that version
> 
> I fixed the problem by doing a workaround to install jdk 17 with the mc-server script, works, but it's not ideal

How did you do that? I'd like to try as well.

**Comment by JonasCardoso** [comment] 2021-12-01 21:15
> > > > how to do this manually ? i tried use 'FROM openjdk:17-jdk-buster', but dont work @MiniGPT
> > > 
> > > 
> > > Balena probably didn't release java 17, but I think that fabric 1.18 is using java 16 , maybe try using that version
> > 
> > 
> > I fixed the problem by doing a workaround to install jdk 17 with the mc-server script, works, but it's not ideal
> 
> How did you do that? I'd like to try as well.
put code below before java commands in mc-server/start.sh, works, but it's not ideal

curl -s "https://get.sdkman.io" | bash &&  source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 17.0.1-oracle

**Comment by JustToasty** [comment] 2021-12-02 01:19
> > > > > how to do this manually ? i tried use 'FROM openjdk:17-jdk-buster', but dont work @MiniGPT
> > > > 
> > > > 
> > > > Balena probably didn't release java 17, but I think that fabric 1.18 is using java 16 , maybe try using that version
> > > 
> > > 
> > > I fixed the problem by doing a workaround to install jdk 17 with the mc-server script, works, but it's not ideal
> > 
> > 
> > How did you do that? I'd like to try as well.
> > put code below before java commands in mc-server/start.sh, works, but it's not ideal
> 
> curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 17.0.1-oracle

I tried running that command and got this error, any idea whats wrong?

`root@balenaminecraftserver:~# curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 17.0.1-oracle

                                -+syyyyyyys:
                            `/yho:`       -yd.
                         `/yh/`             +m.
                       .oho.                 hy                          .`
                     .sh/`                   :N`                `-/o`  `+dyyo:.
                   .yh:`                     `M-          `-/osysoym  :hs` `-+sys:      hhyssssssssy+
                 .sh:`                       `N:          ms/-``  yy.yh-      -hy.    `.N-````````+N.
               `od/`                         `N-       -/oM-      ddd+`     `sd:     hNNm        -N:
              :do`                           .M.       dMMM-     `ms.      /d+`     `NMMs       `do
            .yy-                             :N`    ```mMMM.      -      -hy.       /MMM:       yh
          `+d+`           `:/oo/`       `-/osyh/ossssssdNMM`           .sh:         yMMN`      /m.
         -dh-           :ymNMMMMy  `-/shmNm-`:N/-.``   `.sN            /N-         `NMMy      .m/
       `oNs`          -hysosmMMMMydmNmds+-.:ohm           :             sd`        :MMM/      yy
      .hN+           /d:    -MMMmhs/-.`   .MMMh   .ss+-                 `yy`       sMMN`     :N.
     :mN/           `N/     `o/-`         :MMMo   +MMMN-         .`      `ds       mMMh      do
    /NN/            `N+....--:/+oooosooo+:sMMM:   hMMMM:        `my       .m+     -MMM+     :N.
   /NMo              -+ooooo+/:-....`...:+hNMN.  `NMMMd`        .MM/       -m:    oMMN.     hs
  -NMd`                                    :mm   -MMMm- .s/     -MMm.       /m-   mMMd     -N.
 `mMM/                                      .-   /MMh. -dMo     -MMMy        od. .MMMs..---yh
 +MMM.                                           sNo`.sNMM+     :MMMM/        sh`+MMMNmNm+++-
 mMMM-                                           /--ohmMMM+     :MMMMm.       `hyymmmdddo
 MMMMh.                  ````                  `-+yy/`yMMM/     :MMMMMy       -sm:.``..-:-.`
 dMMMMmo-.``````..-:/osyhddddho.           `+shdh+.   hMMM:     :MmMMMM/   ./yy/` `:sys+/+sh/
 .dMMMMMMmdddddmmNMMMNNNNNMMMMMs           sNdo-      dMMM-  `-/yd/MMMMm-:sy+.   :hs-      /N`
  `/ymNNNNNNNmmdys+/::----/dMMm:          +m-         mMMM+ohmo/.` sMMMMdo-    .om:       `sh
     `.-----+/.`       `.-+hh/`         `od.          NMMNmds/     `mmy:`     +mMy      `:yy.
           /moyso+//+ossso:.           .yy`          `dy+:`         ..       :MMMN+---/oys:
         /+m:  `.-:::-`               /d+                                    +MMMMMMMNh:`
        +MN/                        -yh.                                     `+hddhy+.
       /MM+                       .sh:
      :NMo                      -sh/
     -NMs                    `/yy:
    .NMy                  `:sh+.
   `mMm`               ./yds-
  `dMMMmyo:-.````.-:oymNy:`
  +NMMMMMMMMMMMMMMMMms:`
    -+shmNMMMNmdy+:`


                                                                 Now attempting installation...


Looking for a previous installation of SDKMAN...
Looking for unzip...
Looking for zip...
Not found.
==============================================================================
 Please install zip on your system using your favourite package manager.

 Restart after installing zip.
==============================================================================`

**Comment by JonasCardoso** [comment] 2021-12-02 01:24
> > > > > > how to do this manually ? i tried use 'FROM openjdk:17-jdk-buster', but dont work @MiniGPT
> > > > > 
> > > > > 
> > > > > Balena probably didn't release java 17, but I think that fabric 1.18 is using java 16 , maybe try using that version
> > > > 
> > > > 
> > > > I fixed the problem by doing a workaround to install jdk 17 with the mc-server script, works, but it's not ideal
> > > 
> > > 
> > > How did you do that? I'd like to try as well.
> > > put code below before java commands in mc-server/start.sh, works, but it's not ideal
> > 
> > 
> > curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 17.0.1-oracle
> 
> I tried running that command and got this error, any idea whats wrong?
> 
> ![image](https://user-images.githubusercontent.com/50493368/144340175-80c3caef-f4cb-4776-93a9-e707fdd3631b.png)

sorry, i forgot mention that need install the zip package put code bellow in mc-server/Dockerfile.template
RUN install_packages wget jq zip

**Comment by stevereno30** [comment] 2021-12-02 12:41
Every time my machine restarts, it re-installs mc-server which over writes all changes to Dockerfile.template and start.sh. Any idea how I can disable this behavior?

**Comment by te-ce** [comment] 2021-12-02 17:56
Where do I find mc-server?
via WinSCP I get only these directors

**Comment by stevereno30** [comment] 2021-12-02 18:28
The actual serverfiles are located at /usr/src/serverfiles

**Comment by te-ce** [comment] 2021-12-02 19:04
![image](https://user-images.githubusercontent.com/9517685/144486469-f71d9af3-c0da-4755-b511-530a408e5a80.png)

huh?

**Comment by te-ce** [comment] 2021-12-02 19:14
so in root should lay a Dockerfile.template ? I don't have one. Or should I just create it?

in usr/src is no serverfiles
![image](https://user-images.githubusercontent.com/9517685/144487823-0df11017-ba06-4f9d-9fa1-4796a21fee1d.png)

**Comment by parkerbailey** [comment] 2021-12-02 20:25
> > > > > > > how to do this manually ? i tried use 'FROM openjdk:17-jdk-buster', but dont work @MiniGPT
> > > > > > 
> > > > > > 
> > > > > > Balena probably didn't release java 17, but I think that fabric 1.18 is using java 16 , maybe try using that version
> > > > > 
> > > > > 
> > > > > I fixed the problem by doing a workaround to install jdk 17 with the mc-server script, works, but it's not ideal
> > > > 
> > > > 
> > > > How did you do that? I'd like to try as well.
> > > > put code below before java commands in mc-server/start.sh, works, but it's not ideal
> > > 
> > > 
> > > curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 17.0.1-oracle
> > 
> > 
> > I tried running that command and got this error, any idea whats wrong?
> > ![image](https://user-images.githubusercontent.com/50493368/144340175-80c3caef-f4cb-4776-93a9-e707fdd3631b.png)
> 
> sorry, i forgot mention that need install the zip package put code bellow in mc-server/Dockerfile.template RUN install_packages wget jq zip

Every time the service is restarted, it reverts back to java 16 and no longer has zip or sdk installed. How can we make these changes persist through the service restart?

**Comment by JonasCardoso** [comment] 2021-12-02 20:27
you need deploy with theses changes from source

**Comment by parkerbailey** [comment] 2021-12-02 20:36
> you need deploy with theses changes from source

Are you referring to creating a new release in the source code and pushing it from the balena-cli? Or is there something else you mean by source?

**Comment by JonasCardoso** [comment] 2021-12-02 20:43
> > you need deploy with theses changes from source
> 
> Are you referring to creating a new release in the source code and pushing it from the balena-cli? Or is there something else you mean by source?

"creating a new release in the source code and pushing it from the balena-cli"

**Comment by fogdog-twilight** [comment] 2021-12-03 13:53
After all, how can I install java17?

**Comment by stevereno30** [comment] 2021-12-03 14:14
> After all, how can I install java17?

This is how I did it:
`wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
tar xzf OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
rm -r /usr/local/openjdk-16
cp ./jdk-17.0.1+12 /usr/local/openjdk-16
wget https://papermc.io/api/v2/projects/paper/versions/1.18/builds/25/downloads/paper-1.18-25.jar
rm /usr/src/serverfiles/paper.jar
rm /usr/src/serverfiles/papersha256.txt
cp ./paper-1.18-25.jar /usr/src/serverfiles/paper.jar
echo '90606f2be5d5306a85febe016a84be6f081f544ff2085292fba9ec83b9cf31f4 paper.jar' > /usr/src/serverfiles/papersha256.txt`

This is what those commands do: 1) download java 17. 2) unpack downloaded tar.gz. 3) remove java 16. 4) move java 17 into the place that 16 was (the reason it is moved as "java 16" is because the start.sh file is looking for a directory named "openjdk-16"). 5) download most recent paper.jar. 6) delete mc-server's paper.jar. 7) delete mc-server's sha256 file. 8) move downloaded paper.jar into place. 9) create new sha256 file for downloaded paper.jar.

**Comment by tom7351** [comment] 2021-12-03 21:19
> > After all, how can I install java17?
> 
> This is how I did it:
> Open mc-server from the balena dashboard terminal and enter these commands* one by one:
> ```
> wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
> tar xzf OpenJDK17U-jdk_x64_linux_hotspot_17.0.1_12.tar.gz
> rm -rf /usr/local/openjdk-16
> cp ./jdk-17.0.1+12 /usr/local/openjdk-16
> wget https://papermc.io/api/v2/projects/paper/versions/1.18/builds/25/downloads/paper-1.18-25.jar
> rm /usr/src/serverfiles/paper.jar
> rm /usr/src/serverfiles/papersha256.txt
> cp ./paper-1.18-25.jar /usr/src/serverfiles/paper.jar
> echo '90606f2be5d5306a85febe016a84be6f081f544ff2085292fba9ec83b9cf31f4 paper.jar' > /usr/src/serverfiles/papersha256.txt
> 
> ```
> 
> *This is what those commands do: 1) download java 17 from adoptium.net's github. 2) unpack downloaded tar.gz. 3) remove java 16. 4) move java 17 into the place that 16 was (the reason it is moved as "java 16" is because the start.sh file is looking for a directory named "openjdk-16"). 5) download most recent (as of 12/3/2021) paper.jar from papermc.io. 6) delete mc-server's paper.jar. 7) delete mc-server's sha256 file. 8) move downloaded paper.jar into place. 9) create new sha256 file for downloaded paper.jar. 
> 
> Finally you must stop, then restart the mc-server service. Don't reboot, or this process will have to be repeated.

It tells me is is a read only file system when i try to wget.

**Comment by stevereno30** [comment] 2021-12-03 21:31
> 
The host OS is read-only. You have to use the mc-server
![image](https://user-images.githubusercontent.com/5103600/144675384-4672b13f-4dd9-45c8-9f68-f2823e9fe857.png)

**Comment by fogdog-twilight** [comment] 2021-12-04 01:51
java 17 is still not installed.

In my environment, openjdk-16 not exist and "java --version" command is not available.
But, balena console said "System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9-24) Host: Linux 5.10.78-v8 (aarch64)"

**Comment by stevereno30** [comment] 2021-12-04 01:53
Interesting. My balena install is relatively new and vanilla. Maybe 2 months old? Do you have balena updates available?

**Comment by fogdog-twilight** [comment] 2021-12-04 02:46
Host OS version
balenaOS 2.87.16+rev1

Supervisor version
12.11.16

I think my balena is latest version.

**Comment by stevereno30** [comment] 2021-12-04 16:27
That's odd. This is what mine looks like:

![Screenshot_20211204-102350~2](https://user-images.githubusercontent.com/5103600/144716958-b5e3ebf9-19df-4547-8dc5-8962352f63db.png)

I wonder if balena is somehow organized differently based on hardware? My server is running on an old desktop PC.

**Comment by AlexProgrammerDE** [comment] 2021-12-04 17:44
Latest commits resolved the java 17 issue. Please redeploy your applications and your server should work just fine!

**Comment by AlexProgrammerDE** [comment] 2021-12-19 20:51
Going to close this now as the issue is resolved.

**Closed** 2021-12-19 20:52 UTC
Labels: bug
